### ISSUE TITLE
Resolve outstanding reasonable Codacy issues

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-workflow#15]
- [ ] resolve all issues that make sense
  - style issues
  - unused imports and variables
- [ ] document in this issue suggested changes to Codacy configuration to avoid unreasonable issues 

https://app.codacy.com/gh/virtool/virtool-workflow/issues

**Comment by BlakeASmith** [comment]
D203 (blank line required before class docstring) and D211 (no blank lines allowed before class docstring) 
are in conflict, so we will need to disable one of them. 

Here is an issue pyCQA/pydocstyle describing the conflict further

https://github.com/PyCQA/pydocstyle/issues/141

**Comment by BlakeASmith** [comment]
The issue "arguments differ from overridden __fixture__ method" (W0221) cannot be easily resolved due to the nature of how workflow fixtures are implemented. 

__fixture__ is defined on the `WorkflowFixture` base class to accept (*args, **kwargs) as arguments, since fixtures may depend on other fixtures themselves. The required fixtures are provided based on the parameter names of the overridden `__fixture__` method. 

Here are the related issues from pylint:

https://github.com/PyCQA/pylint/issues/3737
https://github.com/PyCQA/pylint/issues/1553

**Comment by BlakeASmith** [comment]
D212 (multi line doc-string should start on second line) and D213(multi line doc-string should start on first line) are also in conflict, so one of them needs to be ignored. 

https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts

**Comment by BlakeASmith** [comment]
I'd also suggest disabling the `list-item-indent` warning, or changing the setting to expect a single space between the bullet and the test. 

As of now it expects 3 spaces between the bullet and the text in markdown lists. 

- This list item is currently invalid
-   This list item is valid
