### ISSUE TITLE
Base Image for Workflows with Bundled Runtime.

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#29]
It should include:

- Dependencies for virtool_workflow_runtime.
- Commonly used programs such as `fastqc` and `skewer`.
- Access to conda and bioconda.
- Any commonly used PPAs or equivalent.
- Preset ENTRYPOINT to start the runtime.

It should be optimized to be as small as possible while still making it
easy for workflow developers to install additional software.

**Comment by BlakeASmith** [comment]
We need to decide on a distribution to start from. 

[python:3.7-slim-buster](https://github.com/docker-library/python/blob/7392a0441706ffe66862c37e6d8ceb4d5b1c4389/3.7/buster/slim/Dockerfile) may be a good starting point.

**Comment by igboyes** [comment]
> Access to conda and bioconda

This should be provided as an example, but not be included in a minimal base image. Provide example of installing with bioconda using [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/).

> Any commonly used PPAs or equivalent

Provide an example of this instead of including. I am not sure this is really even necessary as almost no bioinformatics software is distributed via APT or other Linux package managers.

**Comment by igboyes** [comment]
> We need to decide on a distribution to start from. I'm thinking something debian based.
> 
> [python:3.7-slim-buster](https://github.com/docker-library/python/blob/7392a0441706ffe66862c37e6d8ceb4d5b1c4389/3.7/buster/slim/Dockerfile) may be a good starting point.

I'm wondering if we should just go with 3.9...

**Comment by BlakeASmith** [comment]
> > We need to decide on a distribution to start from. I'm thinking something debian based.
> > [python:3.7-slim-buster](https://github.com/docker-library/python/blob/7392a0441706ffe66862c37e6d8ceb4d5b1c4389/3.7/buster/slim/Dockerfile) may be a good starting point.
> 
> I'm wondering if we should just go with 3.9...

There's no obvious reason not to as I see it.
