### ISSUE TITLE
Method for running a process that can start any workflow

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-workflow#45]
I will refer to this process as a runner but naming can be revised.

# Features
- allow configuration of what Redis lists the runner will listen on
- runner determines which workflow container to run based on job document fetched from MongoDB
- allow configuration of what resources the runner will be limited to

Write up concept in this issue.

**Comment by BlakeASmith** [comment]
# Runner for Arbitrary Workflows 

Though a cloud deployment of Virtool is planned, It is still of benefit to allow some users to manage their own deployments within their own network. As such we require a mechanism for launching any workflow within that local deployment. 

The approach planned for the cloud deployment is not suitable for a local
deployment as it requires a separate `runner` instance for each workflow type. The
additional instances do not pose a problem in the cloud deployment since a
larger number of running workflows means that the overhead of starting and
stopping `runner` instances is minimal. However this overhead can be avoided in
a local deployment by having a single process start and stop workflow containers
as needed. 


# How It Could Work

1. The `runner` process listens on a **Redis** list for new job IDs.
2. A specific workflow to run is specified in the **MongoDB** job document.
3. A docker image for the particular workflow is obtained if not already
   present.
4. The `runner` process uses the Docker API to start a container and run the Workflow. 

The number of parallel jobs can be scaled by spinning up additional instances of the generic runner. 

# Problems to Address

Before a generic workflow runner can be implemented a some problems need to be
addressed. 

## Building the Workflow Images

Issue #29 addresses the need for a base image which will be used. The generic
workflow `runner` will require a uniform interface for starting all workflow
containers. In other words all of the images must have the same `ENTRYPOINT`
command. 

## Distribution of Workflow Images

The `runner` must have access to each of the images for each workflow type. The
images must also have an identifier which can be used in the *MongoDB* job
document to specify the which image to use. 

Ideally, we should be able to add new workflow types without requiring an update
to the `runner`. As such it makes sense to acquire the workflow images on demand
as apposed to pre-loading them. In other words, we shouldn't hard code a list of
images to pull within the `runner` application if it can be avoided.

If a set list of workflows is to be avoided, then the identifier used to specify
the workflow must contain enough information for the runner to be able to find
and pull/build the images. 

I suggest setting up a Docker Registry containing any approved
workflow images. Then the name of the image in that registry can be used 
as the identifier. 

The [Github Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry) could be used for this purpose, though it is currently in public beta.
