### ISSUE TITLE
Workflow fixtures documentation clarification

### ISSUE THREAD

**Issue by jakeale** [virtool/virtool-workflow#89]
In the fixtures documentation it describes several built-in fixtures, some of which I've been using are `data_path` and `temp_path`. 

In the [detailed usage](https://github.com/virtool/virtool-workflow/tree/master/virtool_workflow/fixtures#storage) it shows that `data_path` is being imported directly from `virtool_workflow.storage.paths`. When I try to use it as it is described the import gets marked as an unused in my IDE as well as Codacy, and the fixture still seems to be accessible when the import is removed.

Does the detailed usage represent an older implementation of these fixtures?

**Comment by BlakeASmith** [comment]
> In the fixtures documentation it describes several built-in fixtures, some of which I've been using are `data_path` and `temp_path`.
> 
> In the [detailed usage](https://github.com/virtool/virtool-workflow/tree/master/virtool_workflow/fixtures#storage) it shows that `data_path` is being imported directly from `virtool_workflow.storage.paths`. When I try to use it as it is described the import gets marked as an unused in my IDE as well as Codacy, and the fixture still seems to be accessible when the import is removed.
> 
> Does the detailed usage represent an older implementation of these fixtures?

A fixture will be available for use as long as there is a reference to it's class stored in the enclosing, or global, scope. In practice this means that as long as the module containing the fixture has been imported the fixture can be used. 

The IDE is showing the `unused import error` as it considers the `data_path` parameter to be a local variable
of the function and does not consider it a usage of the `data_path` fixture from module scope. 

When python imports a module a reference to that module is stored in `sys.modules`. Upon another import of that 
same module, `sys.modules` will be checked first and the module's code will not be executed a second time. Additionaly using the `from ... import ...` syntax also imports the entire module and stores a `ModuleType` object into `sys.modules`.

What this means for us is that as long as the module containing a specific fixture (such as `data_path`) has been imported at **any point** in the execution of the program the fixture will be available, regardless of whether or not it was imported within the `workflow` module. 

The runtime for `virtool_workflow` will implicitly import all of the documented fixtures prior to executing the workflow defined in the `workflow.py` file. It will also import the `fixtures.py` file prior to running. This means that when using `workflow run` to execute your workflow, the `data_path` fixture and others will already be available. However, when running outside of the runtime context those modules will not be implicitly imported, which is why I included the import statements in the documentation.


Also the import mechanism was previously a bit broken and did not consistently import the required modules. The implicit imports are now working as of the `0.3.0` release. There has also been a `runtime` pytest fixture included in
`virtool_workflow_runtime.test_utils` which will load all fixtures which would be present in the runtime environment.

A section describing how to use the `runtime` pytest fixture is now given in the [fixture docs](https://github.com/virtool/virtool-workflow/tree/master/virtool_workflow/fixtures#the-runtime-pytest-fixture).


I think at this point that the explicit imports in the docs have become misleading. I will remove them from the examples. I'll also add a section on how to avoid the `unused import` warning when pulling in additional fixtures.
